# Generated by Django 4.2 on 2023-05-20 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1)),
                ('adress', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_date', models.DateTimeField(auto_now_add=True)),
                ('symptom', models.TextField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.resident')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_1', models.FloatField()),
                ('ind_2', models.FloatField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.enrollment')),
            ],
        ),
    ]
